spring:
  datasource:
    url: jdbc:postgresql://localhost:8000/db_phone_shop
    username: phone-shop
    password: Liisor$22
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml
