spring:
  datasource:
    url: jdbc:postgresql://localhost:8000/phoneshop_night
    username: phone-shope
    password: Liisor$22
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update